export type Breakpoint = "desktop" | "laptop" | "tablet" | "mobileLandscape" | "mobile";
export type ResponsiveOverride = { paddingY?: number; radius?: number; opacity?: number; blur?: number; scale?: number; rotate?: number; offsetX?: number; offsetY?: number; hidden?: boolean };
export type BusinessModule = { id:string; title:string; industries:string[]; category:"booking"|"commerce"|"content"|"lead"|"operations"; backend:boolean; features:string[] };
export const BREAKPOINTS: Record<Exclude<Breakpoint,"desktop">, string> = { laptop:"(max-width: 1280px)", tablet:"(max-width: 1024px)", mobileLandscape:"(max-width: 900px) and (orientation: landscape)", mobile:"(max-width: 640px)" };
export const BUSINESS_MODULES: BusinessModule[] = [
 {id:"restaurant-reservations",title:"Tischreservierungen",industries:["Gastronomie"],category:"booking",backend:true,features:["Tische & Sitzplätze","Personenzahl","Zeitslots","Kapazitätsprüfung","Sperrzeiten","Stornierung"]},
 {id:"restaurant-menu",title:"Digitale Speisekarte",industries:["Gastronomie"],category:"content",backend:true,features:["Kategorien","Gerichte","Preise","Allergene","Verfügbarkeit"]},
 {id:"appointments",title:"Terminbuchung",industries:["Beauty","Praxis","Tattoo","Automotive"],category:"booking",backend:true,features:["Mitarbeiter","Leistungen","Dauer","Verfügbarkeit","Puffer","Stornierung"]},
 {id:"real-estate",title:"Objekte & Besichtigungen",industries:["Immobilien"],category:"operations",backend:true,features:["Objekte","Filter","Exposé","Status","Besichtigungstermine","Leads"]},
 {id:"fitness-booking",title:"Kurse & Probetraining",industries:["Fitness"],category:"booking",backend:true,features:["Kurse","Trainer","Kapazität","Warteliste","Probetraining"]},
 {id:"service-configurator",title:"Leistungs-Konfigurator",industries:["Handwerk","Reinigung"],category:"lead",backend:true,features:["Leistungsauswahl","Objektdaten","Uploads","Terminwunsch","Lead-Zusammenfassung"]},
 {id:"commerce",title:"Shop & Checkout",industries:["Alle"],category:"commerce",backend:true,features:["Produkte","Varianten","Bestand","Warenkorb","Checkout","Bestellungen"]},
 {id:"ai-assistant",title:"KI-Assistent",industries:["Alle"],category:"lead",backend:true,features:["FAQ","Beratung","Lead-Qualifizierung","Übergabe"]},
 {id:"hotel-booking",title:"Zimmer & Aufenthalte",industries:["Hotel","Ferienwohnung"],category:"booking",backend:true,features:["Zimmer","Belegung","Nächte","Gäste","Preise","Anfrage/Checkout"]},
 {id:"vouchers",title:"Gutscheine",industries:["Beauty","Gastronomie","Fitness","Tattoo"],category:"commerce",backend:true,features:["Werte","Codes","Einlösung","Status"]},
 {id:"reviews",title:"Bewertungen",industries:["Alle"],category:"content",backend:false,features:["Testimonials","Bewertungsquellen","Trust-Elemente"]},
 {id:"newsletter",title:"Newsletter",industries:["Alle"],category:"lead",backend:true,features:["Opt-in","Listen","Provider-Anbindung"]},
 {id:"customer-portal",title:"Kundenportal",industries:["Alle"],category:"operations",backend:true,features:["Projektstatus","Dokumente","Rechnungen","Support","Freigaben"]},
];
export const modulesForIndustry=(industry:string)=>BUSINESS_MODULES.filter(m=>m.industries.includes("Alle")||m.industries.includes(industry));
export function responsiveCss(pages:any[]){let css=""; for(const [bp,mq] of Object.entries(BREAKPOINTS)){let chunk=""; for(const p of pages||[]) for(const s of p.sections||[]){const o=s.responsive?.[bp] as ResponsiveOverride|undefined;if(!o)continue;const rules:string[]=[];if(o.paddingY!=null)rules.push(`padding-top:${o.paddingY}px`,`padding-bottom:${o.paddingY}px`);if(o.radius!=null)rules.push(`border-radius:${o.radius}px`);if(o.opacity!=null)rules.push(`opacity:${o.opacity}`);if(o.blur!=null)rules.push(`filter:blur(${o.blur}px)`);if(o.hidden!=null)rules.push(`display:${o.hidden?"none":""}`);if(o.scale!=null||o.rotate!=null||o.offsetX!=null||o.offsetY!=null)rules.push(`transform:translate(${o.offsetX??0}px,${o.offsetY??0}px) scale(${(o.scale??100)/100}) rotate(${o.rotate??0}deg)`);if(rules.length)chunk+=`[data-jx-section="${s.id}"]{${rules.join(";")}}\n`; } if(chunk)css+=`@media ${mq}{${chunk}}\n`; } return css;}
export function compileCode(config:any){const json=JSON.stringify(config,null,2);const runtime=`"use client";\nimport React from "react";\nexport function JXProductionSite({config}:{config:any}){const page=config.pages?.find((p:any)=>p.id===(config.activePage||"home"))||config.pages?.[0];const sections=page?.sections||[];return <main className="jx-production" style={{background:config.colors?.background||"#0b0b0b",color:config.colors?.text||"#fff",fontFamily:config.fonts?.body||"Arial,sans-serif"}}><header className="jx-header"><strong>{config.company||"JX Site"}</strong><nav>{(config.pages||[]).map((p:any)=><a key={p.id} href={p.id==="home"?"/":"/"+p.id}>{p.name}</a>)}</nav></header>{sections.filter((s:any)=>!s.hidden).map((s:any)=><section key={s.id} data-jx-section={s.id} className={'jx-section jx-'+s.kind}><div className="jx-inner"><small>{s.kind?.toUpperCase()}</small><h2>{s.content?.headline||config.content?.headline||config.company||"Willkommen"}</h2><p>{s.content?.copy||config.content?.subheadline||""}</p></div></section>)}</main>}\n`;
const css=`.jx-production{min-height:100vh}.jx-header{height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 5vw;border-bottom:1px solid #ffffff1a}.jx-header nav{display:flex;gap:22px}.jx-header a{color:inherit;text-decoration:none}.jx-section{padding:90px 5vw}.jx-inner{max-width:1200px;margin:auto}.jx-inner h2{font-size:clamp(2.4rem,6vw,6rem);line-height:.95;margin:.3em 0}.jx-inner p{max-width:720px;font-size:1.1rem;opacity:.75}`+responsiveCss(config.pages||[]);
return {
 "lib/jx-site-config.ts":`export const siteConfig = ${json} as const;\n`,
 "components/jx-production-site.tsx":runtime,
 "styles/jx-runtime.css":css,
 "app/page.tsx":`import "@/styles/jx-runtime.css";\nimport { siteConfig } from "@/lib/jx-site-config";\nimport { JXProductionSite } from "@/components/jx-production-site";\nexport default function Page(){return <JXProductionSite config={siteConfig} />}`,
 "jx-configuration.json":json,
 "jx-qa-manifest.json":JSON.stringify({version:1,breakpoints:[1440,1280,1024,900,640],requireSameRuntime:true,sections:(config.pages||[]).flatMap((p:any)=>(p.sections||[]).map((s:any)=>({page:p.id,id:s.id,kind:s.kind})))},null,2)
};}
