import { createHmac, timingSafeEqual, randomBytes } from "node:crypto";
import { eq } from "drizzle-orm";
import { getDb } from "@/db";
import { orders, projects, projectVersions, invoices } from "@/db/schema";
function valid(raw:string,header:string,secret:string){const parts=Object.fromEntries(header.split(",").map(x=>x.split("=",2))) as Record<string,string>;if(!parts.t||!parts.v1)return false;const expected=createHmac("sha256",secret).update(`${parts.t}.${raw}`).digest("hex");const a=Buffer.from(expected),b=Buffer.from(parts.v1);return a.length===b.length&&timingSafeEqual(a,b)}
export async function POST(request: Request) {
  const secret=process.env.STRIPE_WEBHOOK_SECRET, signature=request.headers.get("stripe-signature"), raw=await request.text();
  if(!secret||!signature||!valid(raw,signature,secret)) return new Response("Invalid webhook",{status:400});
  try { const event=JSON.parse(raw) as any; if(event.type==="checkout.session.completed"){const session=event.data.object;const db=getDb();const email=session.customer_details?.email||"";await db.update(orders).set({status:"paid",customerEmail:email,stripeSubscriptionId:typeof session.subscription==="string"?session.subscription:null,invoiceStatus:session.subscription?"active":"not_applicable"}).where(eq(orders.stripeSessionId,session.id));const [order]=await db.select().from(orders).where(eq(orders.stripeSessionId,session.id)).limit(1);if(order){const [existing]=await db.select().from(projects).where(eq(projects.orderId,order.id)).limit(1);if(!existing){const token=randomBytes(24).toString("hex");const cfg=order.configuration||"{}";const [project]=await db.insert(projects).values({orderId:order.id,customerEmail:email,name:"JX Studio Website-Projekt",status:"paid",configuration:cfg,portalToken:token}).returning({id:projects.id});await db.insert(projectVersions).values({projectId:project.id,version:1,configuration:cfg,note:"Projekt aus bezahltem Checkout erstellt"});}}}
    if(event.type==="invoice.payment_failed" && event.data.object?.subscription){const db=getDb();await db.update(orders).set({invoiceStatus:"payment_failed"}).where(eq(orders.stripeSubscriptionId,String(event.data.object.subscription)));}
    if(event.type==="invoice.paid" && event.data.object?.subscription){const db=getDb(),inv=event.data.object;await db.update(orders).set({invoiceStatus:"active"}).where(eq(orders.stripeSubscriptionId,String(inv.subscription)));const [o]=await db.select().from(orders).where(eq(orders.stripeSubscriptionId,String(inv.subscription))).limit(1);if(o&&inv.id){await db.insert(invoices).values({orderId:o.id,stripeInvoiceId:String(inv.id),customerEmail:inv.customer_email||o.customerEmail,amount:Number(inv.amount_paid||0),currency:String(inv.currency||"eur"),status:"paid",hostedUrl:inv.hosted_invoice_url||null,pdfUrl:inv.invoice_pdf||null,periodStart:inv.period_start?new Date(inv.period_start*1000):null,periodEnd:inv.period_end?new Date(inv.period_end*1000):null}).onConflictDoNothing();}}
    if(event.type==="customer.subscription.deleted"){const db=getDb();await db.update(orders).set({invoiceStatus:"cancelled"}).where(eq(orders.stripeSubscriptionId,String(event.data.object.id)));} return Response.json({received:true}); }
  catch(error){console.error("stripe_webhook_failed",error);return new Response("Webhook failed",{status:400});}
}
